DROP TABLE IF EXISTS `three_vertex`;
DROP TABLE IF EXISTS `four_vertex`;
DROP TABLE IF EXISTS `five_vertex`;
DROP TABLE IF EXISTS `six_vertex`;
DROP TABLE IF EXISTS `seven_vertex`;
DROP TABLE IF EXISTS `eight_vertex`;

CREATE TABLE `three_vertex` (
  `id_3v` int NOT NULL AUTO_INCREMENT,
  `graph_num` int NOT NULL,
  `is_bipartite` varchar(5) NOT NULL,
  `num_edges` int NOT NULL,
  `diameter` int NOT NULL,
  `clique_num` int NOT NULL,
  `is_distance_regular` varchar(5) NOT NULL,
  `is_eulerian` varchar(5) NOT NULL,
  `cut_vertice_list` varchar(200) NOT NULL,
  `num_cut_vertices` int NOT NULL,
  `cycle_basis` varchar(200) NOT NULL,
  `degree_sequence` varchar(200) NOT NULL,
  `aut_group_generator` varchar(200) NOT NULL,
  `grp_size1` int NOT NULL,
  `grp_size2` int NOT NULL,
  `orbits` varchar(200) NOT NULL,
  `num_orbits` int NOT NULL,
  `3_cycle_size_str` int NOT NULL,
  PRIMARY KEY (`id_3v`),
  UNIQUE KEY `id_3v_UNIQUE` (`id_3v`),
  UNIQUE KEY `graph_num_UNIQUE` (`graph_num`)
) ENGINE=InnoDB , DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `four_vertex` (
  `id_4v` int NOT NULL AUTO_INCREMENT,
  `graph_num` int NOT NULL,
  `is_bipartite` varchar(5) NOT NULL,
  `num_edges` int NOT NULL,
  `diameter` int NOT NULL,
  `clique_num` int NOT NULL,
  `is_distance_regular` varchar(5) NOT NULL,
  `is_eulerian` varchar(5) NOT NULL,
  `cut_vertice_list` varchar(200) NOT NULL,
  `num_cut_vertices` int NOT NULL,
  `cycle_basis` varchar(200) NOT NULL,
  `degree_sequence` varchar(200) NOT NULL,
  `aut_group_generator` varchar(200) NOT NULL,
  `grp_size1` int NOT NULL,
  `grp_size2` int NOT NULL,
  `orbits` varchar(200) NOT NULL,
  `num_orbits` int NOT NULL,
  `3_cycle_size_str` int NOT NULL,
  `4_cycle_size_str` int NOT NULL,
  PRIMARY KEY (`id_4v`),
  UNIQUE KEY `id_4v_UNIQUE` (`id_4v`),
  UNIQUE KEY `graph_num_UNIQUE` (`graph_num`)
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `five_vertex` (
  `id_5v` int NOT NULL AUTO_INCREMENT,
  `graph_num` int NOT NULL,
  `is_bipartite` varchar(5) NOT NULL,
  `num_edges` int NOT NULL,
  `diameter` int NOT NULL,
  `clique_num` int NOT NULL,
  `is_distance_regular` varchar(5) NOT NULL,
  `is_eulerian` varchar(5) NOT NULL,
  `cut_vertice_list` varchar(200) NOT NULL,
  `num_cut_vertices` int NOT NULL,
  `cycle_basis` varchar(200) NOT NULL,
  `degree_sequence` varchar(200) NOT NULL,
  `aut_group_generator` varchar(200) NOT NULL,
  `grp_size1` int NOT NULL,
  `grp_size2` int NOT NULL,
  `orbits` varchar(200) NOT NULL,
  `num_orbits` int NOT NULL,
  `3_cycle_size_str` int NOT NULL,
  `4_cycle_size_str` int NOT NULL,
  `5_cycle_size_str` int NOT NULL,
  PRIMARY KEY (`id_5v`),
  UNIQUE KEY `id_5v_UNIQUE` (`id_5v`),
  UNIQUE KEY `graph_num_UNIQUE` (`graph_num`)
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `six_vertex` (
  `id_6v` int NOT NULL AUTO_INCREMENT,
  `graph_num` int NOT NULL,
  `is_bipartite` varchar(5) NOT NULL,
  `num_edges` int NOT NULL,
  `diameter` int NOT NULL,
  `clique_num` int NOT NULL,
  `is_distance_regular` varchar(5) NOT NULL,
  `is_eulerian` varchar(5) NOT NULL,
  `cut_vertice_list` varchar(200) NOT NULL,
  `num_cut_vertices` int NOT NULL,
  `cycle_basis` varchar(200) NOT NULL,
  `degree_sequence` varchar(200) NOT NULL,
  `aut_group_generator` varchar(200) NOT NULL,
  `grp_size1` int NOT NULL,
  `grp_size2` int NOT NULL,
  `orbits` varchar(200) NOT NULL,
  `num_orbits` int NOT NULL,
  `3_cycle_size_str` int NOT NULL,
  `4_cycle_size_str` int NOT NULL,
  `5_cycle_size_str` int NOT NULL,
  `6_cycle_size_str` int NOT NULL,
  PRIMARY KEY (`id_6v`),
  UNIQUE KEY `id_6v_UNIQUE` (`id_6v`),
  UNIQUE KEY `graph_num_UNIQUE` (`graph_num`)
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `seven_vertex` (
  `id_7v` int NOT NULL AUTO_INCREMENT,
  `graph_num` int NOT NULL,
  `is_bipartite` varchar(5) NOT NULL,
  `num_edges` int NOT NULL,
  `diameter` int NOT NULL,
  `clique_num` int NOT NULL,
  `is_distance_regular` varchar(5) NOT NULL,
  `is_eulerian` varchar(5) NOT NULL,
  `cut_vertice_list` varchar(200) NOT NULL,
  `num_cut_vertices` int NOT NULL,
  `cycle_basis` varchar(200) NOT NULL,
  `degree_sequence` varchar(200) NOT NULL,
  `aut_group_generator` varchar(200) NOT NULL,
  `grp_size1` int NOT NULL,
  `grp_size2` int NOT NULL,
  `orbits` varchar(200) NOT NULL,
  `num_orbits` int NOT NULL,
  `3_cycle_size_str` int NOT NULL,
  `4_cycle_size_str` int NOT NULL,
  `5_cycle_size_str` int NOT NULL,
  `6_cycle_size_str` int NOT NULL,
  `7_cycle_size_str` int NOT NULL,
  PRIMARY KEY (`id_7v`),
  UNIQUE KEY `id_7v_UNIQUE` (`id_7v`),
  UNIQUE KEY `graph_num_UNIQUE` (`graph_num`)
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `eight_vertex` (
  `id_8v` int NOT NULL AUTO_INCREMENT,
  `graph_num` int NOT NULL,
  `is_bipartite` varchar(5) NOT NULL,
  `num_edges` int NOT NULL,
  `diameter` int NOT NULL,
  `clique_num` int NOT NULL,
  `is_distance_regular` varchar(5) NOT NULL,
  `is_eulerian` varchar(5) NOT NULL,
  `cut_vertice_list` varchar(200) NOT NULL,
  `num_cut_vertices` int NOT NULL,
  `cycle_basis` varchar(200) NOT NULL,
  `degree_sequence` varchar(200) NOT NULL,
  `aut_group_generator` varchar(200) NOT NULL,
  `grp_size1` int NOT NULL,
  `grp_size2` int NOT NULL,
  `orbits` varchar(200) NOT NULL,
  `num_orbits` int NOT NULL,
  `3_cycle_size_str` int NOT NULL,
  `4_cycle_size_str` int NOT NULL,
  `5_cycle_size_str` int NOT NULL,
  `6_cycle_size_str` int NOT NULL,
  `7_cycle_size_str` int NOT NULL,
  `8_cycle_size_str` int NOT NULL,
  PRIMARY KEY (`id_8v`),
  UNIQUE KEY `id_8v_UNIQUE` (`id_8v`),
  UNIQUE KEY `graph_num_UNIQUE` (`graph_num`)
) ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;